### ISSUE TITLE
Switch the events to interfaces

### ISSUE THREAD

**Issue by jamierocks** [FountainMC/FountainAPI#22]
Forge already has some events, so we will need to make them interfaces (might be an idea to look at Sponge's way of handling this).

We should probably also make the actual EventBus an interface too.

**Comment by phase** [comment]
I think classes are easier to work with on the plugin side. If I want to fire an arbitrary event, all I have to do is instantiate an object. Implementing an interface seems like a lot more work.

For Forge, instead of having the existing events implement ours, you could fire both at the same time. It might not be ideal, but it saves us from creating 30 interface events and 30 class events that only implement those.

The EventBus is in Event4J. We'd have to recreate that if we wanted to change it to an interface

**Comment by jamierocks** [comment]
Sponge's solution involves having a factory for constructing events. infact they event have a generator for the event factory

**edit**: https://github.com/SpongePowered/event-impl-gen

**Comment by phase** [comment]
That's a lot of complexity to add when we can just use objects. One extra object is better than a generator for factories that create interfaces.

**Comment by jamierocks** [comment]
One extra object + passing things in between the two events buses

**Comment by wgaylord** [comment]
We could just take a forge dev environment for making additions to forge and add our API into it... then not much needs to be done.

**Comment by jamierocks** [comment]
Thats a horrible idea :|

**Comment by Techcable** [comment]
Interfaces are fine, since plugins shouldn't be constructing events in the first place.
This makes it much much easier for a forge implementation, or a bukkit compatibility wrapper.
As for ease of creation, we can just add factory methods to that returns a default implementation:

``` java
public static BlockBreakEvent create(BlockPosition position, BlockState state) {
    return new BlockBreakEvent() {
        public BlockPosition getPosition() {
            return position;
        }

        public BlockPosition getState() {
            return state;
        }
    }
}
```

Since its anonymous, plugins won't be able to access it but its just as easy to create as a new class.
We don't need to have some crazy factory manager thingy with auto-generated implementations.
This is the easiest way to be compatible with alternate event systems without  over-complicating the main implementation.

**Comment by minecrafter** [comment]
@Techcable what about plugins using the event system to plug in their own events, such as Votifier?

**Comment by phase** [comment]
@minecrafter Plugins can still fire their events using the [EventManager](https://github.com/FountainMC/FountainAPI/blob/master/src/main/java/org/fountainmc/api/event/EventManager.java), and all they need to do is create a class that implements Event or an Event subinterface.
