### ISSUE TITLE
Project development is starting again?

### ISSUE THREAD

**Issue by PizzaCrust** [FountainMC/FountainAPI#31]

**Comment by Techcable** [comment]
Yup, but I can't do it alone!
The new primary implementation is [TacoFountain](https://github.com/FountainMC/TacoFountain), which is based on Bukkit. I want to get a working product out as soon as possible, so there'll be more energy and enthusiasm behind development. It'll also help us guide the development of the API better, since we'll be able to get working plugins out faster.

**Comment by phase** [comment]
Is FountainCommon out?

**Comment by Techcable** [comment]
FountainCommon won't really work with TacoFountain, though it'd still be useful for a forge implementation or a vanilla reimplementation.

**Comment by jamierocks** [comment]
I'll be working on FountainMod (vanilla server mod) when 1.12 drops.

**Comment by PizzaCrust** [comment]
Will the complete code base across the Fountain project be refactored/made in Kotlin?

**Comment by Techcable** [comment]
@PizzaCrust Yes, most of the code will be in kotlin unless others choose to write it in java.

**Comment by phase** [comment]
@jamierocks Based off of Spigot's 1.12 build?

@Techcable I think limiting our codebases to a safe language would be better for everyone. I'm 100% down for 100% Kotlin.

**Comment by jamierocks** [comment]
@phase No, FountainMod will be it's own server mod.

**Comment by Techcable** [comment]
Kotlin's not inherently safer than correctly programmed java, so I don't think it's necessary to require it 100%, especially since the minecraft server itself is written in java.

**Comment by PizzaCrust** [comment]
@Techcable can you fix travis 😄 please

**Comment by wgaylord** [comment]
this alive again..... Also I agree with Techcable... (Considering I see no reason to mix two langs... Even if they run on the same VM)
