### ISSUE TITLE
Switch to Slf4J

### ISSUE THREAD

**Issue by PizzaCrust** [FountainMC/FountainAPI#6]
What logging system?

**Comment by Techcable** [comment]
[Slf4j](http://www.slf4j.org/) so we aren't tied to a specific logging implementation.
Bukkit uses java.util.Logger, and they have to do hackery/trickery to get it to work with log4j.
Slf4j is unarguably the best since we don't tie implementations to a specific logging implementation (and it has a nice API).

**Comment by PizzaCrust** [comment]
Slf4j Log4j implementation?

**Comment by phase** [comment]
Minecraft has a LogManager class which we could add a getter for in the Fountain class.

**Comment by PizzaCrust** [comment]
You'd have to add Log4j as a dependency to your POM.

**Comment by Techcable** [comment]
No, we want to wrap log4j with Slf4J.
Slf4j is an interface/API, log4j is an implementation.
Actually, log4j doesn't directly implement slf4j, you need to use [a wrapper](http://slf4j.org/api/org/slf4j/impl/Log4jLoggerAdapter.html).

**Comment by Techcable** [comment]
Fixed as of edb137ab4a348ed5915b144554a7959f28415d72
